--------------------------------------------------------
  
--------------------------------------------------------
DROP TABLE shopmaster."ATTACHMENT" cascade constraints;
DROP TABLE shopmaster."BANK" cascade constraints;
DROP TABLE shopmaster."CART" cascade constraints;
DROP TABLE shopmaster."MEMBER" cascade constraints;
DROP TABLE shopmaster."O_ORDER" cascade constraints;
DROP TABLE shopmaster."O_ORDER_LIST" cascade constraints;
DROP TABLE shopmaster."PRODUCT" cascade constraints;
DROP TABLE shopmaster."PURCHASE" cascade constraints;
DROP TABLE shopmaster."REVIEW" cascade constraints;
DROP TABLE shopmaster."SALE_LIST" cascade constraints;
--------------------------------------------------------
--  DDL for Table ATTACHMENT
--------------------------------------------------------

  CREATE TABLE shopmaster."ATTACHMENT" 
   (	"ATT_NO" NUMBER, 
	"ATT_NAME" VARCHAR2(100 BYTE), 
	"ATT_DATE" DATE DEFAULT SYSDATE, 
	"ATT_LEVEL" NUMBER(1,0), 
	"ATT_STATUS" CHAR(1 BYTE) DEFAULT 'Y', 
	"PRODUCT_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BANK
--------------------------------------------------------

  CREATE TABLE shopmaster."BANK" 
   (	"BANK_CODE" VARCHAR2(30 BYTE), 
	"BANK_NAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CART
--------------------------------------------------------

  CREATE TABLE shopmaster."CART" 
   (	"CART_NO" NUMBER, 
	"MEMBER_NO" NUMBER, 
	"CART_QUANTITY" NUMBER, 
	"CART_SIZE" CHAR(1 BYTE), 
	"PRODUCT_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE shopmaster."MEMBER" 
   (	"MEMBER_NO" NUMBER, 
	"MEMBER_ID" VARCHAR2(30 BYTE), 
	"MEMBER_NICKNAME" VARCHAR2(30 BYTE), 
	"MEMBER_PW" VARCHAR2(100 BYTE), 
	"MEMBER_NAME" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"PHONE" VARCHAR2(13 BYTE), 
	"ADDRESS" VARCHAR2(300 BYTE), 
	"ENROLL_DATE" DATE DEFAULT SYSDATE, 
	"BRAND_NAME" VARCHAR2(30 BYTE) DEFAULT '중고', 
	"ACCOUNT_NUMBER" VARCHAR2(30 BYTE), 
	"LOGIN_TYPE" NUMBER, 
	"BANK_CODE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table O_ORDER
--------------------------------------------------------

  CREATE TABLE shopmaster."O_ORDER" 
   (	"ORDER_NO" NUMBER, 
	"RECEIVER_NAME" VARCHAR2(15 BYTE), 
	"ORDER_ADDRESS" VARCHAR2(300 BYTE), 
	"ORDER_DATE" DATE DEFAULT SYSDATE, 
	"ORDER_MEMO" VARCHAR2(60 BYTE), 
	"TOTAL_PRICE" NUMBER, 
	"MEMBER_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table O_ORDER_LIST
--------------------------------------------------------

  CREATE TABLE shopmaster."O_ORDER_LIST" 
   (	"ORDER_SIZE" CHAR(1 BYTE), 
	"ORDER_QUANTITY" NUMBER, 
	"ORDER_NO" NUMBER, 
	"PRODUCT_NO" NUMBER, 
	"ORDER_STATUS" NUMBER DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE shopmaster."PRODUCT" 
   (	"PRODUCT_NO" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(100 BYTE), 
	"PRODUCT_DETAIL" VARCHAR2(2000 BYTE), 
	"PRODUCT_SIZEINFO" VARCHAR2(2000 BYTE), 
	"PRODUCT_SIZE" VARCHAR2(10 BYTE), 
	"PRODUCT_PRICE" NUMBER, 
	"product_stock_240" NUMBER, 
	"product_stock_250" NUMBER, 
	"product_stock_260" NUMBER, 
	"PRODUCT_TYPE" NUMBER DEFAULT 2, 
	"MEMBER_NO" NUMBER, 
	"PRODUCT_STATUS" CHAR(1 BYTE) DEFAULT 'Y', 
	"PRODUCT_CATEGORY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PURCHASE
--------------------------------------------------------

  CREATE TABLE shopmaster."PURCHASE" 
   (	"ORDER_NO" NUMBER, 
	"PURCHASE_STATUS" NUMBER DEFAULT 1, 
	"MEMBER_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REVIEW
--------------------------------------------------------

  CREATE TABLE shopmaster."REVIEW" 
   (	"REVIEW_NO" NUMBER, 
	"REVIEW_CONTENTS" VARCHAR2(1000 BYTE), 
	"REVIEW_DATE" DATE DEFAULT SYSDATE, 
	"REVIEW_TITLE" VARCHAR2(100 BYTE), 
	"MEMBER_NO" NUMBER, 
	"PRODUCT_NO" NUMBER, 
	"ORDER_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SALE_LIST
--------------------------------------------------------

  CREATE TABLE shopmaster."SALE_LIST" 
   (	"ORDER_NO" NUMBER, 
	"SALE_STATUS" NUMBER DEFAULT 1, 
	"MEMBER_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into shopmaster.ATTACHMENT
SET DEFINE OFF;

REM INSERTING into shopmaster.BANK
SET DEFINE OFF;
Insert into shopmaster.BANK (BANK_CODE,BANK_NAME) values ('KB','KB');
Insert into shopmaster.BANK (BANK_CODE,BANK_NAME) values ('SH','신한');
Insert into shopmaster.BANK (BANK_CODE,BANK_NAME) values ('WR','우리');
Insert into shopmaster.BANK (BANK_CODE,BANK_NAME) values ('CH','축협');
Insert into shopmaster.BANK (BANK_CODE,BANK_NAME) values ('SU','수협');
Insert into shopmaster.BANK (BANK_CODE,BANK_NAME) values ('IBK','IBK');
Insert into shopmaster.BANK (BANK_CODE,BANK_NAME) values ('NH','농협');
REM INSERTING into shopmaster.CART
SET DEFINE OFF;

REM INSERTING into shopmaster.MEMBER
SET DEFINE OFF;

--------------------------------------------------------
--  DDL for Index PK_ATTACHMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX shopmaster."PK_ATTACHMENT" ON shopmaster."ATTACHMENT" ("ATT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_BANK
--------------------------------------------------------

  CREATE UNIQUE INDEX shopmaster."PK_BANK" ON shopmaster."BANK" ("BANK_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011046
--------------------------------------------------------

  CREATE UNIQUE INDEX shopmaster."SYS_C0011046" ON shopmaster."BANK" ("BANK_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CART
--------------------------------------------------------

  CREATE UNIQUE INDEX shopmaster."PK_CART" ON shopmaster."CART" ("CART_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_MEMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX shopmaster."PK_MEMBER" ON shopmaster."MEMBER" ("MEMBER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011057
--------------------------------------------------------

  CREATE UNIQUE INDEX shopmaster."SYS_C0011057" ON shopmaster."MEMBER" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011058
--------------------------------------------------------

  CREATE UNIQUE INDEX shopmaster."SYS_C0011058" ON shopmaster."MEMBER" ("MEMBER_NICKNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011059
--------------------------------------------------------

  CREATE UNIQUE INDEX shopmaster."SYS_C0011059" ON shopmaster."MEMBER" ("MEMBER_PW") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011060
--------------------------------------------------------

  CREATE UNIQUE INDEX shopmaster."SYS_C0011060" ON shopmaster."MEMBER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011061
--------------------------------------------------------

  CREATE UNIQUE INDEX shopmaster."SYS_C0011061" ON shopmaster."MEMBER" ("PHONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011062
--------------------------------------------------------

  CREATE UNIQUE INDEX shopmaster."SYS_C0011062" ON shopmaster."MEMBER" ("ACCOUNT_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ORDER
--------------------------------------------------------

  CREATE UNIQUE INDEX shopmaster."PK_ORDER" ON shopmaster."O_ORDER" ("ORDER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PRODUCT
--------------------------------------------------------

  CREATE UNIQUE INDEX shopmaster."PK_PRODUCT" ON shopmaster."PRODUCT" ("PRODUCT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011075
--------------------------------------------------------

  CREATE UNIQUE INDEX shopmaster."SYS_C0011075" ON shopmaster."PRODUCT" ("PRODUCT_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PURCHASE
--------------------------------------------------------

  CREATE UNIQUE INDEX shopmaster."PK_PURCHASE" ON shopmaster."PURCHASE" ("ORDER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_REVIEW
--------------------------------------------------------

  CREATE UNIQUE INDEX shopmaster."PK_REVIEW" ON shopmaster."REVIEW" ("REVIEW_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_SALE_LIST
--------------------------------------------------------

  CREATE UNIQUE INDEX shopmaster."PK_SALE_LIST" ON shopmaster."SALE_LIST" ("ORDER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TRG_PRODUCT_STOCK
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER shopmaster."TRG_PRODUCT_STOCK" 
AFTER INSERT
ON O_ORDER_LIST
FOR EACH ROW
    BEGIN
        IF :NEW.ORDER_SIZE = 'S'
        THEN 
            UPDATE PRODUCT
            SET product_stock_240 = 
            CASE 
                WHEN product_stock_240 - :NEW.ORDER_QUANTITY < 0 THEN 0
                WHEN product_stock_240 - :NEW.ORDER_QUANTITY >= 0 THEN product_stock_240 - :NEW.ORDER_QUANTITY
            END
            WHERE PRODUCT_NO = :NEW.PRODUCT_NO;
        END IF;
        IF :NEW.ORDER_SIZE = 'M' 
        THEN 
            UPDATE PRODUCT
            SET product_stock_250 = 
            CASE 
                WHEN product_stock_250 - :NEW.ORDER_QUANTITY < 0 THEN 0
                WHEN product_stock_250 - :NEW.ORDER_QUANTITY >= 0 THEN product_stock_250 - :NEW.ORDER_QUANTITY
            END
            WHERE PRODUCT_NO = :NEW.PRODUCT_NO;
        END IF;
        IF :NEW.ORDER_SIZE = 'L' 
        THEN 
            UPDATE PRODUCT
            SET product_stock_260 = 
            CASE 
                WHEN product_stock_260 - :NEW.ORDER_QUANTITY < 0 THEN 0
                WHEN product_stock_260 - :NEW.ORDER_QUANTITY >= 0 THEN product_stock_260 - :NEW.ORDER_QUANTITY
            END
            WHERE PRODUCT_NO = :NEW.PRODUCT_NO;
        END IF;
    END;

/
ALTER TRIGGER shopmaster."TRG_PRODUCT_STOCK" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_ORDER_STATUS_REVIEW
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER shopmaster."TRG_ORDER_STATUS_REVIEW" 
AFTER INSERT
ON REVIEW
FOR EACH ROW
    BEGIN
        UPDATE O_ORDER_LIST
        SET ORDER_STATUS = 4
        WHERE :NEW.PRODUCT_NO = PRODUCT_NO
        AND :NEW.ORDER_NO = ORDER_NO;
    END;

/
ALTER TRIGGER shopmaster."TRG_ORDER_STATUS_REVIEW" ENABLE;
--------------------------------------------------------
--  Constraints for Table ATTACHMENT
--------------------------------------------------------

  ALTER TABLE shopmaster."ATTACHMENT" ADD CONSTRAINT "PK_ATTACHMENT" PRIMARY KEY ("ATT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE shopmaster."ATTACHMENT" ADD CHECK (ATT_STATUS IN('Y','N')) ENABLE;
  ALTER TABLE shopmaster."ATTACHMENT" ADD CONSTRAINT "SYS_C009443" CHECK (ATT_LEVEL IN('1','2','3','4')) ENABLE;
  ALTER TABLE shopmaster."ATTACHMENT" MODIFY ("PRODUCT_NO" NOT NULL ENABLE);
  ALTER TABLE shopmaster."ATTACHMENT" MODIFY ("ATT_STATUS" NOT NULL ENABLE);
  ALTER TABLE shopmaster."ATTACHMENT" MODIFY ("ATT_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BANK
--------------------------------------------------------

  ALTER TABLE shopmaster."BANK" ADD UNIQUE ("BANK_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE shopmaster."BANK" ADD CONSTRAINT "PK_BANK" PRIMARY KEY ("BANK_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE shopmaster."BANK" MODIFY ("BANK_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE shopmaster."CART" ADD CONSTRAINT "PK_CART" PRIMARY KEY ("CART_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE shopmaster."CART" ADD CHECK (CART_SIZE IN('S','M','L')) ENABLE;
  ALTER TABLE shopmaster."CART" MODIFY ("PRODUCT_NO" NOT NULL ENABLE);
  ALTER TABLE shopmaster."CART" MODIFY ("CART_SIZE" NOT NULL ENABLE);
  ALTER TABLE shopmaster."CART" MODIFY ("MEMBER_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE shopmaster."MEMBER" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE shopmaster."MEMBER" ADD UNIQUE ("MEMBER_NICKNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE shopmaster."MEMBER" ADD UNIQUE ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE shopmaster."MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY ("MEMBER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE shopmaster."MEMBER" ADD CHECK (LOGIN_TYPE IN ('1','2')) ENABLE;
  ALTER TABLE shopmaster."MEMBER" MODIFY ("LOGIN_TYPE" NOT NULL ENABLE);
  ALTER TABLE shopmaster."MEMBER" MODIFY ("BRAND_NAME" NOT NULL ENABLE);
  ALTER TABLE shopmaster."MEMBER" MODIFY ("ENROLL_DATE" NOT NULL ENABLE);
  ALTER TABLE shopmaster."MEMBER" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE shopmaster."MEMBER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE shopmaster."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE shopmaster."MEMBER" MODIFY ("MEMBER_PW" NOT NULL ENABLE);
  ALTER TABLE shopmaster."MEMBER" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table O_ORDER
--------------------------------------------------------

  ALTER TABLE shopmaster."O_ORDER" ADD CONSTRAINT "PK_ORDER" PRIMARY KEY ("ORDER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE shopmaster."O_ORDER" MODIFY ("MEMBER_NO" NOT NULL ENABLE);
  ALTER TABLE shopmaster."O_ORDER" MODIFY ("TOTAL_PRICE" NOT NULL ENABLE);
  ALTER TABLE shopmaster."O_ORDER" MODIFY ("ORDER_DATE" NOT NULL ENABLE);
  ALTER TABLE shopmaster."O_ORDER" MODIFY ("ORDER_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE shopmaster."O_ORDER" MODIFY ("RECEIVER_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table O_ORDER_LIST
--------------------------------------------------------

  ALTER TABLE shopmaster."O_ORDER_LIST" MODIFY ("ORDER_STATUS" NOT NULL ENABLE);
  ALTER TABLE shopmaster."O_ORDER_LIST" ADD CHECK (ORDER_SIZE IN('S','M','L')) ENABLE;
  ALTER TABLE shopmaster."O_ORDER_LIST" MODIFY ("PRODUCT_NO" NOT NULL ENABLE);
  ALTER TABLE shopmaster."O_ORDER_LIST" MODIFY ("ORDER_NO" NOT NULL ENABLE);
  ALTER TABLE shopmaster."O_ORDER_LIST" MODIFY ("ORDER_QUANTITY" NOT NULL ENABLE);
  ALTER TABLE shopmaster."O_ORDER_LIST" MODIFY ("ORDER_SIZE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE shopmaster."PRODUCT" ADD UNIQUE ("PRODUCT_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE shopmaster."PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY ("PRODUCT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE shopmaster."PRODUCT" ADD CONSTRAINT "PRODUCT_CAETGORY" CHECK (PRODUCT_CATEGORY IN('1', '2', '3', '4', '5')) ENABLE;
  ALTER TABLE shopmaster."PRODUCT" ADD CHECK (PRODUCT_STATUS IN('Y', 'N')) ENABLE;
  ALTER TABLE shopmaster."PRODUCT" ADD CHECK (PRODUCT_TYPE IN('1', '2')) ENABLE;
  ALTER TABLE shopmaster."PRODUCT" MODIFY ("PRODUCT_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE shopmaster."PRODUCT" MODIFY ("PRODUCT_STATUS" NOT NULL ENABLE);
  ALTER TABLE shopmaster."PRODUCT" MODIFY ("MEMBER_NO" NOT NULL ENABLE);
  ALTER TABLE shopmaster."PRODUCT" MODIFY ("PRODUCT_TYPE" NOT NULL ENABLE);
  ALTER TABLE shopmaster."PRODUCT" MODIFY ("PRODUCT_PRICE" NOT NULL ENABLE);
  ALTER TABLE shopmaster."PRODUCT" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PURCHASE
--------------------------------------------------------

  ALTER TABLE shopmaster."PURCHASE" MODIFY ("PURCHASE_STATUS" NOT NULL ENABLE);
  ALTER TABLE shopmaster."PURCHASE" MODIFY ("MEMBER_NO" NOT NULL ENABLE);
  ALTER TABLE shopmaster."PURCHASE" ADD CHECK (PURCHASE_STATUS IN('1', '2', '3')) ENABLE;
  ALTER TABLE shopmaster."PURCHASE" ADD CONSTRAINT "PK_PURCHASE" PRIMARY KEY ("ORDER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE shopmaster."REVIEW" MODIFY ("REVIEW_NO" NOT NULL ENABLE);
  ALTER TABLE shopmaster."REVIEW" MODIFY ("REVIEW_CONTENTS" NOT NULL ENABLE);
  ALTER TABLE shopmaster."REVIEW" MODIFY ("REVIEW_TITLE" NOT NULL ENABLE);
  ALTER TABLE shopmaster."REVIEW" MODIFY ("MEMBER_NO" NOT NULL ENABLE);
  ALTER TABLE shopmaster."REVIEW" MODIFY ("PRODUCT_NO" NOT NULL ENABLE);
  ALTER TABLE shopmaster."REVIEW" MODIFY ("ORDER_NO" NOT NULL ENABLE);
  ALTER TABLE shopmaster."REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY ("REVIEW_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SALE_LIST
--------------------------------------------------------

  ALTER TABLE shopmaster."SALE_LIST" MODIFY ("SALE_STATUS" NOT NULL ENABLE);
  ALTER TABLE shopmaster."SALE_LIST" MODIFY ("MEMBER_NO" NOT NULL ENABLE);
  ALTER TABLE shopmaster."SALE_LIST" ADD CHECK (SALE_STATUS IN ('1', '2', '3')) ENABLE;
  ALTER TABLE shopmaster."SALE_LIST" ADD CONSTRAINT "PK_SALE_LIST" PRIMARY KEY ("ORDER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ATTACHMENT
--------------------------------------------------------

  ALTER TABLE shopmaster."ATTACHMENT" ADD CONSTRAINT "FK_ATTACHMENT_PRODUCT_NO" FOREIGN KEY ("PRODUCT_NO")
	  REFERENCES shopmaster."PRODUCT" ("PRODUCT_NO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE shopmaster."CART" ADD CONSTRAINT "FK_CART_MEMBER_NO" FOREIGN KEY ("MEMBER_NO")
	  REFERENCES shopmaster."MEMBER" ("MEMBER_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE shopmaster."CART" ADD CONSTRAINT "FK_CART_PRODUCT_NO" FOREIGN KEY ("PRODUCT_NO")
	  REFERENCES shopmaster."PRODUCT" ("PRODUCT_NO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE shopmaster."MEMBER" ADD CONSTRAINT "FK_MEMBER_BANK_CODE" FOREIGN KEY ("BANK_CODE")
	  REFERENCES shopmaster."BANK" ("BANK_CODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table O_ORDER
--------------------------------------------------------

  ALTER TABLE shopmaster."O_ORDER" ADD CONSTRAINT "FK_ORDER_MEMBER_NO" FOREIGN KEY ("MEMBER_NO")
	  REFERENCES shopmaster."MEMBER" ("MEMBER_NO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table O_ORDER_LIST
--------------------------------------------------------

  ALTER TABLE shopmaster."O_ORDER_LIST" ADD CONSTRAINT "FK_ORDER_LIST_ORDER_NO" FOREIGN KEY ("ORDER_NO")
	  REFERENCES shopmaster."O_ORDER" ("ORDER_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE shopmaster."O_ORDER_LIST" ADD CONSTRAINT "FK_ORDER_LIST_PRODUCT_NO" FOREIGN KEY ("PRODUCT_NO")
	  REFERENCES shopmaster."PRODUCT" ("PRODUCT_NO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE shopmaster."PRODUCT" ADD CONSTRAINT "FK_PRODUCT_MEMBER_NO" FOREIGN KEY ("MEMBER_NO")
	  REFERENCES shopmaster."MEMBER" ("MEMBER_NO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PURCHASE
--------------------------------------------------------

  ALTER TABLE shopmaster."PURCHASE" ADD CONSTRAINT "FK_PURCHASE_MEMBER_NO" FOREIGN KEY ("MEMBER_NO")
	  REFERENCES shopmaster."MEMBER" ("MEMBER_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE shopmaster."PURCHASE" ADD CONSTRAINT "FK_PURCHASE_ORDER_NO" FOREIGN KEY ("ORDER_NO")
	  REFERENCES shopmaster."O_ORDER" ("ORDER_NO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE shopmaster."REVIEW" ADD CONSTRAINT "FK_REVIEW_MEMBER_NO" FOREIGN KEY ("MEMBER_NO")
	  REFERENCES shopmaster."MEMBER" ("MEMBER_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE shopmaster."REVIEW" ADD CONSTRAINT "FK_REVIEW_ORDER_NO" FOREIGN KEY ("ORDER_NO")
	  REFERENCES shopmaster."O_ORDER" ("ORDER_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE shopmaster."REVIEW" ADD CONSTRAINT "FK_REVIEW_PRODUCT_NO" FOREIGN KEY ("PRODUCT_NO")
	  REFERENCES shopmaster."PRODUCT" ("PRODUCT_NO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SALE_LIST
--------------------------------------------------------

  ALTER TABLE shopmaster."SALE_LIST" ADD CONSTRAINT "FK_SALE_LIST_MEMBER_NO" FOREIGN KEY ("MEMBER_NO")
	  REFERENCES shopmaster."MEMBER" ("MEMBER_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE shopmaster."SALE_LIST" ADD CONSTRAINT "FK_SALE_LIST_ORDER_NO" FOREIGN KEY ("ORDER_NO")
	  REFERENCES shopmaster."O_ORDER" ("ORDER_NO") ON DELETE CASCADE ENABLE;
